# Generated by Django 3.0.11 on 2020-12-03 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMixing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('statusmixing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Contact.StatusMixing')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('person_name', models.CharField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=254, null=True)),
                ('email_id', models.CharField(blank=True, max_length=254, null=True)),
                ('organisation_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Contact.statusmixing', models.Model),
        ),
        migrations.CreateModel(
            name='CardModel',
            fields=[
                ('statusmixing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Contact.StatusMixing')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('contact_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Contact.Contact')),
            ],
            options={
                'abstract': False,
            },
            bases=('Contact.statusmixing', models.Model),
        ),
    ]
