# Generated by Django 3.0.11 on 2020-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmixing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='statusmixing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
