# Generated by Django 3.0.11 on 2020-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20201203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Card Image'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organisation_name',
            field=models.TextField(blank=True, null=True, verbose_name='Organisation Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='person_name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Person Name'),
        ),
    ]
